spring.application.name=BackEndModelo

# SERVER CONFIGURATION
server.port=${SERVER_PORT:9096}
#server.error.include-binding-errors=always
#server.error.include-exception=true
#server.error.include-message=always
#server.error.include-stacktrace=on_param

#JPA CONFIGURATION
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create



spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.mvc.format.date=yyyy-MM-dd

# Postgresql connection settings
# Local
spring.datasource.hikari.jdbc-url=jdbc:postgresql://${POSTGRES_SERVICE:localhost:5432}/dbbackmodelo
spring.datasource.url=jdbc:postgresql://${POSTGRES_SERVICE:localhost:5432}/dbbackmodelo
spring.datasource.username=${POSTGRES_SERVICE_USER:wandberg}
spring.datasource.password=${POSTGRES_SERVICE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
